#!/usr/bin/env sh

## Description: Sets up the playground.
## Usage: rebuild
## Example: "ddev rebuild"

# If ddev is running, we ask that the user really wants to reset the environment.
if ddev status | grep -q "web"; then
  echo "Drupal Starforge is currently setup. Do you really want to reset the environment? (y/n)"
  read -r answer
  if [ "$answer" != "y" ]; then
    echo "Aborting re-initialization."
    exit
  fi
  ddev stop
  ddev delete -Oy
  rm -r -f vendor $DDEV_DOCROOT composer.* patches.lock.json
fi

ddev start
ddev composer install
ddev composer drupal:recipe-unpack
